// Dhruv's Birthday Casino — content decks
// {p} {q} = random player names injected at runtime. "bday" = birthday boy references Dhruv.
window.DECKS = {

/* ============ KINGS CUP (A–K rules, Hinglish table rules) ============ */
kingsRules: {
  'A': ['Waterfall', 'Everyone drinks in a chain starting with you. Nobody stops till the person before them stops. Aaram se.'],
  '2': ['You', 'Point at anyone. They drink 2 sips.'],
  '3': ['Me', 'Bad luck. You drink 3 sips.'],
  '4': ['Floor', 'Last one to touch the floor drinks 4.'],
  '5': ['Guys', 'All the boys drink 5.'],
  '6': ['Chicks', 'All the girls drink 6.'],
  '7': ['Heaven', 'Last hand up to the sky drinks 7.'],
  '8': ['Mate', 'Pick a drinking partner. They drink whenever you drink, till the next 8.'],
  '9': ['Rhyme', 'Say a word. Circle rhymes one by one. Hesitate ya repeat = drink 5.'],
  '10': ['Categories', 'Pick a category (IPL teams, SRK movies, daaru brands…). Circle answers. First to blank drinks 5.'],
  'J': ['Thumbmaster', 'Put your thumb on the table anytime — last to copy drinks. Power lasts till the next Jack.'],
  'Q': ['Question Master', 'Anyone who answers your questions drinks 3. Power lasts till the next Queen.'],
  'K': ['King’s Cup', 'Pour some of your drink into the King’s Cup. Whoever draws the 4th King finishes the whole cup. Jai ho.']
},

/* ============ WHEEL OF FATE (16 segments) ============ */
wheel: [
  {t:'3 SIPS', k:'fixed', d:'You drink 3 sips. The wheel is merciful today.'},
  {t:'GIVE 5', k:'fixed', d:'Hand out 5 sips, split them however you like. Politics encouraged.'},
  {t:'WATERFALL', k:'fixed', d:'Start a waterfall. Everyone drinks till you stop. Power trip.'},
  {t:'BDAY TAX', k:'fixed', d:'Everyone drinks 2 for Dhruv\u2019s birthday. Dhruv drinks 0. Perks.'},
  {t:'DARE!', k:'dare', d:'The wheel demands a performance.'},
  {t:'SHOT ZONE', k:'fixed', d:'Take a shot or finish your drink. Dealer\u2019s choice nahi — yours.'},
  {t:'IMMUNITY', k:'fixed', d:'You hold an immunity chip. Skip any one penalty tonight. Guard it.'},
  {t:'DARE!', k:'dare', d:'The wheel demands a performance.'},
  {t:'EVERYONE 2', k:'fixed', d:'Everyone at the table drinks 2. Community service.'},
  {t:'SWAP', k:'buddy', d:'Swap drinks with {p}. No smelling first.'},
  {t:'TRUTH', k:'truth', d:'Answer honestly or drink 5.'},
  {t:'DANCE', k:'fixed', d:'Perform one Bollywood hook step, full commitment. Refuse = 5 sips.'},
  {t:'DBL OR 0', k:'coin', d:'The coin decides.'},
  {t:'NEW RULE', k:'fixed', d:'Invent one table rule. Breaking it costs 2 sips. Lasts all night.'},
  {t:'MYSTERY', k:'mystery', d:'???'},
  {t:'FINISH IT', k:'fixed', d:'Finish whatever is in your glass. The wheel has spoken. RIP.'}
],
wheelDares: [
  'Do the Nagin dance for 30 seconds. Full floor commitment.',
  'Speak in a villain accent till your next turn. Slip = 2 sips each time.',
  'Recreate a famous meme face. Table must guess which one, or you drink 3.',
  'Give a dramatic slow-motion walk across the room. Twice.',
  'Sing the next thing you say. Keep singing for 2 minutes.',
  'Do 10 push-ups while someone counts in Hindi commentary voice.',
  'Let the person on your left restyle your hair. It stays 3 rounds.',
  'Deliver a 30-second award speech for "Most Average Person Here".',
  'Imitate 2 people at this table till everyone guesses both.',
  'Propose to the nearest bottle. Make it emotional. Ring optional.',
  'Talk in news-anchor voice and report this party as breaking news.',
  'Do your best item-number move. Hold the final pose for 5 seconds.',
  'Shayari time: 2 original lines about daaru. Must rhyme.',
  'Let the table pick your phone wallpaper for the next hour.',
  'Hold an ice cube till your next turn. Drop = 3 sips.',
  'Say "I\u2019m the hottest person here" to 3 players, dead serious, no laughing.'
],
wheelMystery: [
  'Everyone swaps seats clockwise and drinks 1. Musical chairs, daaru edition.',
  'Silent round: next 2 minutes, every word costs 1 sip. Starting NOW.',
  'Last person to raise their hand drinks 4. GO.',
  'Compliment battle: you and {p} trade compliments till one laughs. Loser drinks 3.',
  'Phone stack! Everyone\u2019s phone in the middle. First to grab theirs drinks 5.',
  'You\u2019re the bartender: refill duty till your next spin. Everyone drinks 1 to your service.',
  'Reverse round: the spin order flips direction. You spin AGAIN right now.',
  'Group photo, your pose choice. Worst poser (you judge) drinks 2.',
  'Double trouble: you and {p} are drink-twins for 3 spins. Match every sip.',
  'Lucky escape: nothing happens... but {p} drinks 2 for laughing.',
  'Everyone points at the drunkest person on 3. Majority target drinks water. Yes, water.',
  'Jackpot reversal: give out sips equal to your spin number position. 6 sips, your call.'
],

/* ============ NEVER HAVE I EVER (drink if you have) ============ */
nhie: [
'Never have I ever ghosted someone who is in this room’s contact list.',
'Never have I ever lied about being "5 minutes away" while still in the shower.',
'Never have I ever drunk-texted an ex and regretted it before sunrise.',
'Never have I ever pretended to know a song at a concert and lip-synced gibberish.',
'Never have I ever stalked someone’s profile so far back I hit 2014.',
'Never have I ever flirted with someone just for the free drink.',
'Never have I ever kissed someone whose name I didn’t know.',
'Never have I ever blamed traffic for a hangover.',
'Never have I ever sent a screenshot to the wrong person — the person IN the screenshot.',
'Never have I ever cried during a Karan Johar movie and denied it.',
'Never have I ever faked a network problem to end a call.',
'Never have I ever had a crush on a friend’s sibling.',
'Never have I ever woken up in clothes I don’t remember putting on.',
'Never have I ever "accidentally" liked a 40-week-old photo.',
'Never have I ever danced on a table. Or fallen off one.',
'Never have I ever told my parents I was at a "study group" while at a party.',
'Never have I ever used someone’s Netflix after breaking up with them.',
'Never have I ever had a situationship I refused to call a situationship.',
'Never have I ever thrown up in an auto, cab, or someone’s car.',
'Never have I ever flirted over work email or Slack.',
'Never have I ever lied in this very game before.',
'Never have I ever kissed two different people in the same week.',
'Never have I ever made out at a wedding. Shaadi season things.',
'Never have I ever pretended my phone died to avoid plans with someone here.',
'Never have I ever gone on a date just for the food.',
'Never have I ever had a dream about someone at this table.',
'Never have I ever been kicked out of a bar, club, or house party.',
'Never have I ever sexted in a family function.',
'Never have I ever lied about my "body count".',
'Never have I ever hooked up with someone from office.',
'Never have I ever said "I love you" without meaning it.',
'Never have I ever skinny dipped.',
'Never have I ever been walked in on. Ya walked in on someone.',
'Never have I ever used dating apps while in a relationship. Swipe of shame.',
'Never have I ever had a one night stand.',
'Never have I ever faked it. You know what.',
'Never have I ever had a crush on someone in this room.',
'Never have I ever drunkenly called my boss or a professor.',
'Never have I ever kissed someone in this room.',
'Never have I ever stolen daaru from my parents’ cabinet and refilled it with water.',
'Never have I ever bunked work with a fake "fever" the day after a party.',
'Never have I ever had a paranormal-level embarrassing autocorrect in a family group.',
'Never have I ever flirted with a bartender for a stronger pour.',
'Never have I ever maintained two relationships ka talking stage at once.',
'Never have I ever cried in an Uber while the driver pretended not to notice.',
'Never have I ever googled myself. Twice this month.',
'Never have I ever been so hungover I swore off daaru forever. Till Friday.',
'Never have I ever made a fake account to check on someone.',
'Never have I ever gotten a tattoo or piercing I hid from my parents.',
'Never have I ever lied about my age — in either direction.',
'Never have I ever been caught checking someone out by that same someone.',
'Never have I ever "rested my eyes" through an entire movie date.',
'Never have I ever kissed a friend’s ex. Code red.',
'Never have I ever practiced a kiss on my hand. Ya pillow.',
'Never have I ever gatecrashed a shaadi or a party.',
'Never have I ever matched with someone at this table on a dating app.',
'Never have I ever sent a risky text and immediately put the phone face down.',
'Never have I ever had a celebrity crush so intense I commented on their posts.',
'Never have I ever re-gifted a gift to the person who gave it to me.',
'Never have I ever fallen asleep mid-makeout.'
],

/* ============ MOST LIKELY TO (point on 3) ============ */
mostly: [
'Most likely to marry for money and call it "compatibility".',
'Most likely to get arrested for something hilarious.',
'Most likely to cry at Dhruv’s wedding. Before the pheras even start.',
'Most likely to text an ex tonight after this game.',
'Most likely to become a crorepati — and hide it from this group.',
'Most likely to flirt their way out of a challan.',
'Most likely to have a secret finsta.',
'Most likely to ditch this group for their partner. Already doing it.',
'Most likely to fall in love on a 3-day Goa trip.',
'Most likely to start a fight at this party and leave before it ends.',
'Most likely to become famous for the wrong reasons.',
'Most likely to forget their own anniversary.',
'Most likely to end up on Bigg Boss. And win it.',
'Most likely to drunk-order 4000 rupees of food tonight.',
'Most likely to have read everyone’s chats if given one chance.',
'Most likely to date two people at once and get caught at a mall.',
'Most likely to leave this party first. Chupke se, without telling.',
'Most likely to say "bas last drink" five times tonight.',
'Most likely to become a yoga-wale spiritual person after 30.',
'Most likely to get a tattoo of a partner’s name. And regret it.',
'Most likely to survive a zombie apocalypse by betraying this group.',
'Most likely to cry tonight. Happy tears count.',
'Most likely to stalk their ex’s new partner right now, mid-party.',
'Most likely to move abroad and forget us in 6 months.',
'Most likely to get caught lying by their own story contradiction.',
'Most likely to hook up tonight.',
'Most likely to send "I’m outside" from their bed.',
'Most likely to have a 25-step skincare routine but no savings.',
'Most likely to fight with a bouncer. And lose. And apologize.',
'Most likely to be a secret crorepati’s backup option.',
'Most likely to dance like nobody’s watching when EVERYONE is watching.',
'Most likely to marry their current crush. Haan, the one we all know about.',
'Most likely to be a terrible wingman and make it about themselves.',
'Most likely to eat the last slice without asking.',
'Most likely to know the gossip before the people involved know.',
'Most likely to take a work call at this party.',
'Most likely to fake-laugh at their boss’s jokes.',
'Most likely to get emotional about Dhruv growing up tonight.',
'Most likely to still be single at 40 by choice. "By choice."',
'Most likely to have the most unhinged search history.',
'Most likely to propose at a cricket match on the big screen.',
'Most likely to join a pyramid scheme enthusiastically.',
'Most likely to lose their phone tonight and find it in the fridge.',
'Most likely to have kissed the most people in this room.',
'Most likely to write a tell-all book about this friend group.',
'Most likely to become everyone’s rich uncle/aunt figure.',
'Most likely to ugly-cry during the birthday cake cutting.',
'Most likely to start a podcast nobody asked for.',
'Most likely to get married first. Ya already secretly engaged.',
'Most likely to remember none of tonight tomorrow.'
],

/* ============ TRUTH OR DARE ============ */
truths: [
'What’s the biggest lie you’ve told someone at this table?',
'Who in this room would you swap lives with, and what’s the first thing you’d do?',
'What’s your most embarrassing drunk story that this group DOESN’T already know?',
'Rate your last date out of 10. Explain the number.',
'Which two people here would make the worst couple? Why?',
'What’s the longest you’ve gone without a shower? Honest.',
'Who was your first crush in this friend group?',
'What’s one thing you’ve done you’d never tell your parents, even now?',
'What’s the most you’ve spent on something stupid? Rupees, exact figure.',
'If your search history from last week was projected right now, what’s the worst thing on it?',
'Who here has the best partner — and who could do better?',
'What’s a secret talent you’ve never shown us? Show it now.',
'What’s the pettiest reason you’ve ended a talking stage?',
'Describe your worst kiss ever. No name needed. Unless we know them.',
'If you had to marry someone in this room tomorrow, who, and what’s the honeymoon plan?',
'What’s your guilty pleasure song? Bonus: it gets played right now.',
'What was your last white lie to your partner or crush?',
'What’s the weirdest thing you find attractive?',
'Have you ever pretended to like a gift from someone here? Which one?',
'Whose relationship in this room do you secretly judge?',
'What’s the most desperate thing you’ve done to get someone’s attention?',
'Tell us about your weirdest dream involving someone we know.',
'What’s your actual screen time? Open settings, show the table.',
'Who in this room would you call to bury a body? Who would you NOT trust?',
'What’s one trend you participated in that haunts you?',
'What’s the most childish thing you still do?',
'Read out your last 3 Google searches. No skipping.',
'Who here is on your "if we’re both single at 35" list?',
'What’s the worst advice you’ve ever given someone here, knowing it was bad?',
'Have you ever snitched on a friend to a parent or boss?',
'Show the last photo in your camera roll. Context required.',
'What’s your most irrational fear?',
'If you could undo one hookup, which one? Era is enough, name optional.',
'What habit of your best friend secretly annoys you the most?',
'What’s the biggest thing you’ve gotten away with?',
'Who texted you last and what did they want? Show if you dare.',
'What movie dialogue have you used on a real date, unironically?',
'What’s the dumbest reason you’ve cried this year?',
'Which notification would ruin your night if it came right now?',
'Confess one thing to the birthday boy. Anything. Now.'
],
dares: [
'Let the table write one text from your phone to anyone in your chats. They pick the person.',
'Do your best item-number performance for 30 seconds. Full commitment.',
'Call the 5th contact in your phone and sing them Happy Birthday — even if it’s not their birthday.',
'Speak only in Shah Rukh Khan dialogues for the next 10 minutes.',
'Let the person on your right redo your hairstyle. It stays till the game ends.',
'Post a story the table chooses. It stays up for 1 hour.',
'Do 10 push-ups while declaring your love for the ceiling fan.',
'Swap one clothing item with the person opposite you.',
'Eat a spoonful of whatever two players mix from the kitchen. Nothing inedible.',
'Give a 1-minute motivational TED talk on "Why I am like this".',
'Let the table check your WhatsApp archived chats list. Just the names.',
'Imitate 3 people in this room till everyone guesses all 3.',
'Propose marriage to the oldest object in this room. Make it emotional.',
'Dance with no music for 45 seconds while everyone watches silently.',
'Talk in a news-anchor voice and report the "breaking news" of this party for 1 minute.',
'Hand your phone to the birthday boy — he sends one emoji to anyone he picks.',
'Do your best standup set about this friend group. 1 minute. Crowd work allowed.',
'Serenade the person to your left with a 90s Bollywood song.',
'Let the group pose you for a photo that becomes someone’s wallpaper for a week.',
'Walk the "ramp" across the room in your most dramatic walk. Twice. Slow-mo once.',
'Reenact your last breakup or rejection as a 30-second play. Solo.',
'Say the alphabet backwards. Every mistake = 1 sip. Max 5.',
'Hold an ice cube in your hand till your next turn. Drop = 3 sips.',
'Let the table give you a new contact name for someone in your phone. It stays a month.',
'Trade drinks with the person whose glass is fullest.',
'Do 15 squats while naming 15 Bollywood movies. One per squat.',
'Voice-note a shayari to the 3rd person in your recent chats. Original shayari only.',
'Be the table’s butler till your next turn. Refills, snacks, "ji huzoor" included.',
'Show everyone your most-used emojis. Explain the top 3.',
'Act out a scene from DDLJ with a player of the table’s choosing.',
'Make up a rap about the birthday boy. Minimum 4 lines. It must rhyme.',
'Let someone draw on your face with (washable) liner. It stays 3 rounds.',
'Try to lick your elbow for 20 seconds. Seriously try.',
'Narrate everything you do in cricket-commentary voice till your next turn.',
'Do your most honest impression of yourself when drunk. Meta, we know.',
'FaceTime a mutual friend who isn’t here and tell them what they’re missing. 30 seconds.',
'Exchange shirts with the person on your left for the next 2 rounds. Bathroom allowed.',
'Let the table scroll your Instagram Explore page for 15 seconds. Out loud reactions allowed.',
'Say "I’m the hottest person here" to each player, one by one, dead serious. No laughing.',
'Attempt a split. Or your version of a split. Commit.'
],

/* ============ ODDS ARE (dares for the odds game) ============ */
oddsDares: [
'lick the floor-adjacent sole of your own chappal... just kidding — lick a lime dipped in salt and chilli',
'send "we need to talk" to a parent and leave it for 10 minutes',
'do 20 burpees right now',
'let the group post anything (one story) from your account',
'finish your drink in one go',
'eat a raw green chilli, no water for 1 minute',
'give your phone to the table for 5 unsupervised minutes',
'call your crush / partner and say "main aa raha hoon" and hang up',
'take a shot chosen and mixed by the birthday boy',
'speak in only questions for the next 15 minutes',
'let someone go through your gallery for 20 seconds',
'swap outfits completely with another player for an hour',
'dance to a full song chosen by the table',
'text your boss "good morning sir" right now, at night',
'be blindfolded and guess 3 players by touching only their faces',
'put your relationship status song on full volume and lip sync',
'drink a mix of 3 drinks on this table, one sip each',
'do your best crying acting for 60 seconds, no laughing',
'message an ex "u up?" and show the reply whenever it comes',
'carry another player piggyback to the kitchen and back',
'let the table set your Instagram bio for 24 hours',
'sniff everyone’s armpit area and rank the top 3 fragrances',
'prank call a food delivery and ask if they deliver "ghar ka khana"',
'hold a plank while two players rest their feet on your back. 30 seconds',
'speak in English accent ("British returned") for 10 minutes',
'show the table your screen time AND your most-used app',
'let the player on your right send one DM from your account to a celebrity',
'eat a spoon of plain mayo / ketchup / whatever sauce the table picks',
'do the Nagin dance for a full minute',
'reveal the most recent photo in your hidden/locked folder... or finish your drink',
'wear your clothes inside-out for the next hour',
'let the table change your phone wallpaper to anything for a week',
'imitate the birthday boy until he personally forgives you',
'take a sip from every drink at this table',
'sing everything you say for the next 10 minutes'
],

/* ============ CHAOS DECK (Picolo-style, {p}/{q} = names) ============ */
chaos: [
{t:'{p}, distribute 4 sips. Royalty for one card.'},
{t:'{p} and {q}, thumb war. Loser drinks 4.'},
{t:'Everyone who has texted an ex this month drinks 3. Honesty system. God is watching.'},
{t:'{p}, name 5 daaru brands in 10 seconds or drink 5.'},
{t:'{p}, swap seats with {q}. Both drink 1 for the inconvenience.'},
{t:'Birthday rule: everyone raise a toast for Dhruv in exactly 3 words. Worst toast (Dhruv judges) drinks 4.'},
{t:'{p}, you are now "Shot ka Shehenshah". You decide who takes the next penalty whenever a tie happens.', virus:true, end:'{p}, your Shehenshah reign ends. Drink 2 as abdication tax.'},
{t:'Whoever has the lowest phone battery drinks 4. Phones out.'},
{t:'{p}, compliment {q} so sincerely that the table believes it. Fail = 3 sips each.'},
{t:'Last person to stand up drinks 3. GO.'},
{t:'{p}, talk for 30 seconds about "Why I’m the best drinker here" without laughing. Laugh = 4 sips.'},
{t:'Everyone wearing black drinks 2. Fashion tax.'},
{t:'{p}, until your next card, end every sentence with "...in bed". Slip = 1 sip each.', virus:true, end:'{p}, you may stop saying "...in bed". The table may be disappointed.'},
{t:'{p} and {q}, stare contest. Blinker drinks 3.'},
{t:'Everyone points at who’s most sober. Majority target drinks 4 to fix it.'},
{t:'{p}, name every player’s phone wallpaper from memory. Each wrong = 1 sip.'},
{t:'Group waterfall! Birthday boy starts.'},
{t:'{p}, do 5 jumping jacks or drink 5. Economy of effort.'},
{t:'Anyone whose name has more than 5 letters drinks 2. Alphabet tax.'},
{t:'{p}, hand your drink to {q}. {q}, take 2 sips of it. Trust exercise.'},
{t:'Everyone who’s been to Goa with this group drinks 2. Everyone who BAILED on a Goa plan drinks 4.'},
{t:'{p}, you’re the Question Master till your next card. Anyone who answers your questions drinks 2.', virus:true, end:'{p}, Question Master powers revoked. Ask one last question for old times’ sake.'},
{t:'{p}, show the table your last emoji used. The table decides if it costs 0 or 3 sips.'},
{t:'Left-handed players drink 2. Right-handed players drink 2. Ambidextrous? Drink 4, show-off.'},
{t:'{p}, trade one secret for immunity: tell something new, or drink 5.'},
{t:'Speed round: {p} names a city, then clockwise everyone names cities. First repeat/blank drinks 4.'},
{t:'{p}, pick someone to be your "drinking twin" for 3 cards. They match your every sip.', virus:true, end:'{p}, your drinking twin is free. Hug it out.'},
{t:'Whoever laughed last drinks 2. Yes, right now. Adjudicate.'},
{t:'{p}, say the most romantic dialogue you know to an empty chair. Full feeling. Or 4 sips.'},
{t:'Everyone drinks as many sips as drinks they’ve had tonight. Max 5. Self-reporting. Beware karma.'},
{t:'{p}, recreate your most-used selfie face. Hold it for 10 seconds while the table rates it.'},
{t:'{q} decides: {p} either sings the national anthem of nonsense (gibberish, 20 sec) or drinks 4.'},
{t:'Everyone who checked their phone in the last 5 minutes drinks 2. Jail.'},
{t:'{p}, until your next card you must call everyone "ji" (Rahul-ji, Sneha-ji). Slip = 1 sip.', virus:true, end:'{p}, the "ji" protocol has ended-ji.'},
{t:'Toast round! Everyone clink and take 1 sip for the birthday boy. Mandatory happiness.'},
{t:'{p}, 10 seconds: name 3 people in this room you’d take to a deserted island. The rest drink 1 for being left behind.'},
{t:'Shortest person distributes 3 sips. Tallest drinks 2. Genetics.'},
{t:'{p}, your laugh is now illegal till your next card. Every laugh = 2 sips.', virus:true, end:'{p}, laughing is legal again. Please update your face.'},
{t:'{p} and {q}, rock paper scissors. Best of 3. Loser drinks 5.'},
{t:'Everyone whose screen time is above 7 hours drinks 3. Show proof or drink 5.'},
{t:'{p}, describe {q}’s dating life in one movie title. {q} drinks 2 if the table approves the title.'},
{t:'FREEZE! Last player to freeze drinks 3. Unfreeze when the next card is drawn.'},
{t:'{p}, order the table: arrange everyone by who came latest tonight. Latest 2 drink 2 each.'},
{t:'Everyone who has a gym membership they don’t use drinks 4. The gym misses you.'},
{t:'{p}, make up a cocktail name for your current drink and pitch it like Shark Tank. Table invests or you drink 3.'},
{t:'Double tax: {p} and {q} drink 2 each for being the most suspiciously quiet.'},
{t:'{p}, until your next card, you can’t say "yaar", "bro", or "dude". Slip = 1 sip.', virus:true, end:'{p}, "yaar bro dude" unlocked. Use responsibly, yaar bro dude.'},
{t:'Everyone take a water sip. Hydration checkpoint. The casino cares. (Mandatory.)'},
{t:'{p}, tell the table your drunk-superpower. The table votes if it’s real. Fake = 3 sips.'},
{t:'Whoever’s birthday is next after Dhruv’s drinks 2 as advance celebration.'},
{t:'{p}, pick: give 6 sips to one person, or 1 sip to six people. Politics.'},
{t:'Everyone who knows Dhruv for over 5 years drinks 3 nostalgic sips. New friends drink 1.'},
{t:'{p}, 15 seconds of standup about {q}. {q} can’t react. Then {q} drinks 2.'},
{t:'Last person who ate something drinks 2. Snack tax.'},
{t:'{p}, text "guess where I am" to a family member. Show the reply later.'},
{t:'Everyone puts a finger up. Drop it if you’ve ever fallen asleep at a party. All droppers drink 2.'},
{t:'{p}, name the last person you stalked online. Or drink 5. We accept silence as drama.'},
{t:'Mirror round: {q} copies everything {p} does for 60 seconds. {p}, be kind. Or don’t.'},
{t:'{p}, finish this: "I would never date someone who..." The table drinks 1 if anyone feels attacked.'},
{t:'House rule: next person to say "Dhruv" (except Dhruv) drinks 2. Spread the word quietly.', virus:true, end:'The "Dhruv" tax is lifted. Say it loud: DHRUV!'},
{t:'{p}, trade phones with {q} till the next card. Locked screens allowed. Sweating allowed.'},
{t:'Everyone who has cried this month drinks 2. Emotional wellness checkpoint.'},
{t:'{p}, your next sip must be taken with no hands. The table may film.'},
{t:'Everyone who owns more than 3 black t-shirts drinks 2. We see you.'},
{t:'{p}, give your most dramatic award-acceptance speech for "Best Friend of Dhruv". 30 seconds. The losers (everyone else) drink 2.'},
{t:'Partner tax: anyone in a relationship drinks 2. Single? Drink 1 and manifest.'},
{t:'{p}, read the room: guess how many total sips were drunk in the last 5 cards. Way off = drink 3, close = give 3.'},
{t:'Everyone switch seats clockwise. Last to sit drinks 2. Musical chairs, daaru edition.'},
{t:'{p}, confess your worst "dil tootne wala" moment in 1 line, or drink 4 and keep your mystery.'},
{t:'Final-boss card: Birthday boy picks any player. That player picks any dare from memory. Settle it. Both drink 2 after.'}
],

/* ============ TRIVIA (MCQ; wrong = 3 sips, right = give 2) ============ */
trivia: [
{c:"Bollywood", q:"In Sholay, what is the name of Basanti’s ghodi?", o:["Dhanno", "Rani", "Bijli", "Chetak"], a:0},
{c:"Bollywood", q:"Which movie gave us \"Mogambo khush hua\"?", o:["Mr. India", "Shaan", "Karma", "Tridev"], a:0},
{c:"Bollywood", q:"DDLJ’s Raj and Simran meet on a trip across which continent?", o:["Europe", "America", "Australia", "Africa"], a:0},
{c:"Bollywood", q:"Who played Munna Bhai’s Circuit?", o:["Arshad Warsi", "Sanjay Dutt", "Boman Irani", "Jimmy Shergill"], a:0},
{c:"Bollywood", q:"\"Kitne aadmi the?\" — how many actually were there?", o:["Two", "Three", "Four", "One"], a:0},
{c:"Bollywood", q:"In 3 Idiots, what does Rancho say to chase instead of success?", o:["Excellence", "Marks", "Money", "Placement"], a:0},
{c:"Bollywood", q:"Which of these is NOT a Khan?", o:["Akshay Kumar", "Saif", "Irrfan", "Zayed"], a:0},
{c:"Bollywood", q:"In Zindagi Na Milegi Dobara, the deep-sea dive happens in which country?", o:["Spain", "Portugal", "Greece", "Italy"], a:0},
{c:"Bollywood", q:"\"Jhakaas\" is whose signature word?", o:["Anil Kapoor", "Jackie Shroff", "Govinda", "Sanjay Dutt"], a:0},
{c:"Bollywood", q:"Andaz Apna Apna: where is Teja’s mark?", o:["Nowhere — \"Teja main hoon, mark idhar hai\"", "Left cheek", "Right hand", "Forehead"], a:0},
{c:"Bollywood", q:"K3G’s tagline: \"It’s all about loving your...\"", o:["Parents", "Family", "Country", "Khandaan"], a:0},
{c:"Bollywood", q:"Shah Rukh’s profession in Swades?", o:["NASA scientist", "Doctor", "Teacher", "ISRO engineer"], a:0},
{c:"Bollywood", q:"Om Shanti Om’s \"ek chutki sindoor\" speech happens at which event?", o:["Filmfare Awards", "A wedding", "A funeral", "A film launch"], a:0},
{c:"Bollywood", q:"\"21 din mein paisa double\" belongs to which Hera Pheri character?", o:["Raju", "Shyam", "Baburao", "Kabira"], a:0},
{c:"Bollywood", q:"Which film’s climax is on a train to Pakistan?", o:["Gadar", "Veer-Zaara", "Bajrangi Bhaijaan", "Raazi"], a:0},
{c:"Bollywood", q:"Rockstar’s Jordan plays his biggest concert in which city?", o:["Prague", "Delhi", "Verona", "Istanbul"], a:0},
{c:"Bollywood", q:"Which film ran 25+ years at Mumbai’s Maratha Mandir?", o:["DDLJ", "Sholay", "Hum Aapke Hain Koun", "KKHH"], a:0},
{c:"Bollywood", q:"In Jab We Met, Geet is from which city?", o:["Bhatinda", "Ludhiana", "Amritsar", "Chandigarh"], a:0},
{c:"Bollywood", q:"Gangs of Wasseypur’s generational war is over which trade?", o:["Coal", "Sand", "Liquor", "Land"], a:0},
{c:"Bollywood", q:"In Queen, Rani’s solo honeymoon starts in which city?", o:["Paris", "Amsterdam", "Prague", "Vienna"], a:0},
{c:"Screen", q:"FRIENDS ka adda — the coffee shop is called?", o:["Central Perk", "Central Park", "Perk Up", "Java Joint"], a:0},
{c:"Screen", q:"Money Heist’s first big heist targets the Royal Mint of...", o:["Spain", "France", "Italy", "Portugal"], a:0},
{c:"Screen", q:"Complete it: \"Winter is ___\" (Game of Thrones)", o:["Coming", "Here", "Cold", "Near"], a:0},
{c:"Screen", q:"How many Infinity Stones does Thanos collect?", o:["6", "5", "7", "8"], a:0},
{c:"Screen", q:"Squid Game’s first game?", o:["Red Light, Green Light", "Tug of War", "Marbles", "Glass Bridge"], a:0},
{c:"Screen", q:"The cunning house at Hogwarts?", o:["Slytherin", "Gryffindor", "Ravenclaw", "Hufflepuff"], a:0},
{c:"Screen", q:"Stranger Things’ parallel dimension is called?", o:["The Upside Down", "The Other Side", "The Dark World", "The Rift"], a:0},
{c:"Screen", q:"Who directed Oppenheimer?", o:["Christopher Nolan", "Denis Villeneuve", "Martin Scorsese", "Ridley Scott"], a:0},
{c:"Screen", q:"Mirzapur: Kaleen Bhaiya’s legal business front?", o:["Carpets", "Sweets", "Transport", "Bricks"], a:0},
{c:"Screen", q:"Sacred Games: \"Kabhi kabhi lagta hai...\"", o:["\"...apun hi bhagwan hai\"", "\"...sab moh maya hai\"", "\"...game khatam hai\"", "\"...apun hi don hai\""], a:0},
{c:"Screen", q:"Panchayat is set in which fictional village?", o:["Phulera", "Phulwari", "Rampur", "Nandgaon"], a:0},
{c:"Screen", q:"Titanic sinks in which ocean?", o:["Atlantic", "Pacific", "Arctic", "Indian"], a:0},
{c:"Music", q:"\"Tum Hi Ho\" is from which film?", o:["Aashiqui 2", "Yaariyan", "Ek Villain", "Raaz 3"], a:0},
{c:"Music", q:"\"Brown Munde\" is by?", o:["AP Dhillon (with Gurinder Gill)", "Honey Singh", "Badshah", "Diljit Dosanjh"], a:0},
{c:"Music", q:"\"Kesariya\" is from which film?", o:["Brahmastra", "Rockstar", "Tamasha", "Animal"], a:0},
{c:"Music", q:"Most-streamed Indian artist on Spotify, year after year?", o:["Arijit Singh", "Badshah", "Neha Kakkar", "AR Rahman"], a:0},
{c:"Music", q:"\"Naatu Naatu\" won the Oscar for...", o:["Best Original Song", "Best Score", "Best Choreography", "Best Picture"], a:0},
{c:"Music", q:"BTS is from which country?", o:["South Korea", "Japan", "China", "Thailand"], a:0},
{c:"Music", q:"\"Shape of You\" singer?", o:["Ed Sheeran", "Justin Bieber", "Shawn Mendes", "Charlie Puth"], a:0},
{c:"Music", q:"\"Tunak Tunak Tun\" is a 90s banger by?", o:["Daler Mehndi", "Mika Singh", "Sukhbir", "Jazzy B"], a:0},
{c:"Music", q:"\"DJ Waley Babu\" — Badshah featured which singer?", o:["Aastha Gill", "Neha Kakkar", "Sunanda Sharma", "Jonita Gandhi"], a:0},
{c:"Music", q:"AR Rahman’s two Oscars came for which film?", o:["Slumdog Millionaire", "Lagaan", "Roja", "127 Hours"], a:0},
{c:"Food", q:"Pani puri in Kolkata is called?", o:["Puchka", "Golgappa", "Gupchup", "Pani ke bataashe"], a:0},
{c:"Food", q:"Slow-cooking biryani sealed under dough is called?", o:["Dum", "Tadka", "Bhuna", "Dhungar"], a:0},
{c:"Food", q:"Momos travelled to India from?", o:["Tibet/Nepal", "China", "Thailand", "Burma"], a:0},
{c:"Food", q:"Butter chicken was invented at which Delhi restaurant?", o:["Moti Mahal", "Karim’s", "Bukhara", "Kake Da Hotel"], a:0},
{c:"Food", q:"The world’s most expensive spice?", o:["Saffron", "Vanilla", "Cardamom", "Truffle salt"], a:0},
{c:"Food", q:"Maggi’s big India ban drama happened in which year?", o:["2015", "2012", "2017", "2019"], a:0},
{c:"Food", q:"Which does NOT belong in chai masala?", o:["Oregano", "Cardamom", "Ginger", "Cloves"], a:0},
{c:"Food", q:"Vada pav was born in which city?", o:["Mumbai", "Pune", "Nashik", "Surat"], a:0},
{c:"Food", q:"Jalebi batter is primarily?", o:["Fermented maida", "Besan", "Sooji", "Rice flour"], a:0},
{c:"Food", q:"Which Indian sweet is officially GI-tagged to Bengal?", o:["Rosogolla", "Gulab jamun", "Jalebi", "Soan papdi"], a:0},
{c:"Daaru", q:"Old Monk is what kind of spirit?", o:["Dark rum", "Whisky", "Brandy", "Vodka"], a:0},
{c:"Daaru", q:"A \"patiala peg\" is roughly how much?", o:["90–120 ml", "30 ml", "60 ml", "180 ml"], a:0},
{c:"Daaru", q:"Tequila is made from which plant?", o:["Agave", "Cactus", "Sugarcane", "Corn"], a:0},
{c:"Daaru", q:"Which Indian state is dry (no alcohol)?", o:["Gujarat", "Goa", "Punjab", "Sikkim"], a:0},
{c:"Daaru", q:"A classic mojito has rum, soda and...", o:["Mint & lime", "Orange & bitters", "Tomato juice", "Coffee"], a:0},
{c:"Daaru", q:"\"Neat\" means serving liquor...", o:["Straight, no ice, room temp", "With ice", "Chilled & shaken", "With water"], a:0},
{c:"Daaru", q:"Real champagne only comes from Champagne, which is in...", o:["France", "Italy", "Spain", "Portugal"], a:0},
{c:"Daaru", q:"Which came first in human history?", o:["Beer", "Whisky", "Vodka", "Gin"], a:0},
{c:"Daaru", q:"The worm-in-the-bottle tradition belongs to...", o:["Mezcal", "Tequila", "Rum", "Absinthe"], a:0},
{c:"Daaru", q:"Hangover ka main scientific villain?", o:["Dehydration + acetaldehyde", "Sugar", "Carbonation", "Mixing cold drinks"], a:0},
{c:"Adult-ish", q:"A kiss burns roughly how many calories a minute?", o:["2–6", "0 — myth", "20–30", "50+"], a:0},
{c:"Adult-ish", q:"The \"cuddle hormone\"?", o:["Oxytocin", "Dopamine", "Cortisol", "Adrenaline"], a:0},
{c:"Adult-ish", q:"Ghosting someone, then reappearing weeks later is...", o:["Zombieing", "Haunting", "Orbiting", "Breadcrumbing"], a:0},
{c:"Adult-ish", q:"Watching someone’s stories but never texting them is...", o:["Orbiting", "Zombieing", "Benching", "Cushioning"], a:0},
{c:"Adult-ish", q:"A \"soft launch\" on Instagram means...", o:["Hinting at a partner without showing their face", "Posting at 2 am", "Quietly launching a startup", "Posting then deleting"], a:0},
{c:"Adult-ish", q:"\"Cuffing season\" is...", o:["Locking down a partner just for winter", "A handcuff trend", "Wedding season", "Gym season"], a:0},
{c:"Adult-ish", q:"A \"beige flag\" is...", o:["A trait that’s weirdly boring, not bad", "A huge red flag", "A good sign", "A fashion choice"], a:0},
{c:"Adult-ish", q:"\"Love bombing\" means...", o:["Overwhelming affection early on to manipulate", "Surprise proposals", "Double texting", "Too many gifts on birthdays"], a:0},
{c:"Adult-ish", q:"Moving a dating-app match to real texting is called taking it...", o:["Off-app", "Offline", "Off-grid", "Off-market"], a:0},
{c:"Adult-ish", q:"\"Situationship\" means...", o:["All the relationship, none of the label", "A long-distance thing", "A gym romance", "An office fling"], a:0},
{c:"Adult-ish", q:"The first modern condom vending machines appeared in...", o:["Germany", "USA", "Japan", "France"], a:0},
{c:"Adult-ish", q:"\"DTR\" stands for...", o:["Define The Relationship", "Down To Relocate", "Date Then Run", "Don’t Text Rishtedaar"], a:0},
{c:"India", q:"The \"City of Nawabs\"?", o:["Lucknow", "Hyderabad", "Bhopal", "Patna"], a:0},
{c:"India", q:"Which Indian city got the first metro?", o:["Kolkata", "Delhi", "Mumbai", "Chennai"], a:0},
{c:"India", q:"The rupee symbol ₹ was adopted in...", o:["2010", "2005", "2008", "2014"], a:0},
{c:"India", q:"India’s highest civilian award?", o:["Bharat Ratna", "Padma Vibhushan", "Param Vir Chakra", "Ashoka Chakra"], a:0},
{c:"India", q:"The Statue of Unity depicts...", o:["Sardar Patel", "Gandhi", "Nehru", "Shivaji"], a:0},
{c:"India", q:"India’s southernmost point?", o:["Indira Point", "Kanyakumari", "Rameswaram", "Lakshadweep"], a:0},
{c:"India", q:"The \"Pink City\"?", o:["Jaipur", "Jodhpur", "Udaipur", "Bikaner"], a:0},
{c:"India", q:"How many time zones does India use?", o:["1", "2", "3", "5"], a:0},
{c:"India", q:"UPI stands for...", o:["Unified Payments Interface", "Universal Payment India", "United Payments Initiative", "Unified Paisa Interface"], a:0},
{c:"India", q:"India’s national anthem was written by...", o:["Rabindranath Tagore", "Bankim Chandra", "Sarojini Naidu", "Subhash Bose"], a:0},
{c:"World", q:"Which country has the most time zones?", o:["France", "Russia", "USA", "China"], a:0},
{c:"World", q:"The largest desert on Earth?", o:["Antarctica", "Sahara", "Gobi", "Thar"], a:0},
{c:"World", q:"Which country famously has zero rivers?", o:["Saudi Arabia", "Egypt", "Australia", "Mongolia"], a:0},
{c:"World", q:"The Great Wall of China is visible from space with the naked eye.", o:["False", "True", "Only at night", "Only in winter"], a:0},
{c:"World", q:"The smallest country in the world?", o:["Vatican City", "Monaco", "Maldives", "San Marino"], a:0},
{c:"World", q:"Which country gifted the Statue of Liberty to the USA?", o:["France", "England", "Spain", "Italy"], a:0},
{c:"World", q:"Australia’s capital?", o:["Canberra", "Sydney", "Melbourne", "Perth"], a:0},
{c:"World", q:"Mount Everest sits on the border of Nepal and...", o:["China (Tibet)", "India", "Bhutan", "Pakistan"], a:0},
{c:"Body & Science", q:"How many hearts does an octopus have?", o:["3", "1", "2", "8"], a:0},
{c:"Body & Science", q:"The human body is roughly what % water?", o:["60%", "40%", "75%", "90%"], a:0},
{c:"Body & Science", q:"Which planet has the shortest day?", o:["Jupiter", "Mercury", "Mars", "Venus"], a:0},
{c:"Body & Science", q:"The only food that basically never spoils?", o:["Honey", "Rice", "Salt", "Pickle"], a:0},
{c:"Body & Science", q:"Bananas are berries. Strawberries are...", o:["Not berries", "Also berries", "Nuts", "Citrus"], a:0},
{c:"Body & Science", q:"Which animal comfortably sleeps standing up?", o:["Horse", "Cow", "Elephant", "Giraffe"], a:0},
{c:"Body & Science", q:"Strongest human muscle by bite force?", o:["Jaw (masseter)", "Biceps", "Tongue", "Thigh"], a:0},
{c:"Body & Science", q:"Alcohol gets absorbed mostly in the...", o:["Small intestine", "Stomach", "Liver", "Mouth"], a:0},
{c:"Body & Science", q:"Goosebumps are caused by...", o:["Tiny muscles at hair roots", "Nerves firing", "Skin shrinking", "Blood rushing"], a:0},
{c:"Body & Science", q:"Which organ breaks down almost all your daaru?", o:["Liver", "Kidneys", "Stomach", "Pancreas"], a:0},
{c:"History", q:"The Taj Mahal was built by...", o:["Shah Jahan", "Akbar", "Aurangzeb", "Humayun"], a:0},
{c:"History", q:"India became independent at what hour?", o:["Midnight", "Dawn", "Noon", "6 pm"], a:0},
{c:"History", q:"First human on the moon?", o:["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"], a:0},
{c:"History", q:"The Titanic sank in...", o:["1912", "1905", "1920", "1931"], a:0},
{c:"History", q:"Delhi’s Red Fort was built by...", o:["Shah Jahan", "Akbar", "Babur", "Jahangir"], a:0},
{c:"History", q:"The Berlin Wall fell in...", o:["1989", "1979", "1991", "1985"], a:0},
{c:"History", q:"Ashoka ruled which empire?", o:["Maurya", "Gupta", "Mughal", "Chola"], a:0},
{c:"History", q:"Which came first?", o:["The pyramids of Giza", "The Great Wall", "The Colosseum", "Stonehenge’s final form"], a:0},
{c:"Internet", q:"Google’s original name?", o:["BackRub", "SearchIt", "WebCrawl", "PageRanker"], a:0},
{c:"Internet", q:"Instagram started life as an app called...", o:["Burbn", "Snapshot", "Filtr", "Photogram"], a:0},
{c:"Internet", q:"Bluetooth is named after a...", o:["Viking king", "Blue whale", "Dentist", "Codename at Intel"], a:0},
{c:"Internet", q:"The first iPhone launched in...", o:["2007", "2005", "2009", "2010"], a:0},
{c:"Internet", q:"YouTube’s first-ever video is...", o:["\"Me at the zoo\"", "\"Charlie bit my finger\"", "A music video", "A cat video"], a:0},
{c:"Internet", q:"WhatsApp is owned by...", o:["Meta", "Google", "Microsoft", "Telegram"], a:0},
{c:"Internet", q:"Most-followed human on Instagram?", o:["Cristiano Ronaldo", "Messi", "Selena Gomez", "Virat Kohli"], a:0},
{c:"Internet", q:"\"www\" stands for...", o:["World Wide Web", "Western World Web", "Wide World Web", "World Web Works"], a:0},
{c:"Internet", q:"Which company makes the AI assistant Claude?", o:["Anthropic", "OpenAI", "Google", "Meta"], a:0},
{c:"Internet", q:"Ctrl+Z does what?", o:["Undo", "Redo", "Zoom", "Sleep"], a:0},
{c:"Mythology", q:"How many heads does Ravana have?", o:["10", "9", "12", "7"], a:0},
{c:"Mythology", q:"Hanuman is the son of which god?", o:["Vayu (wind)", "Agni (fire)", "Indra (rain)", "Surya (sun)"], a:0},
{c:"Mythology", q:"Arjuna’s bow is called...", o:["Gandiva", "Pinaka", "Sharanga", "Vijaya"], a:0},
{c:"Mythology", q:"Ganesha’s vahan (vehicle)?", o:["Mouse", "Peacock", "Bull", "Swan"], a:0},
{c:"Mythology", q:"Who drank the poison from the samudra manthan?", o:["Shiva", "Vishnu", "Indra", "Brahma"], a:0},
{c:"Mythology", q:"Krishna was born in...", o:["Mathura", "Vrindavan", "Dwarka", "Gokul"], a:0},
{c:"Mythology", q:"Goddess of wealth?", o:["Lakshmi", "Saraswati", "Durga", "Parvati"], a:0},
{c:"Mythology", q:"Zeus’s weapon?", o:["Thunderbolt", "Trident", "Hammer", "Bow"], a:0},
{c:"Sports", q:"Dhoni finished the 2011 World Cup with a six over...", o:["Long-on", "Cover", "Square leg", "Mid-wicket"], a:0},
{c:"Sports", q:"Warne’s \"ball of the century\" dismissed...", o:["Mike Gatting", "Graham Gooch", "Alec Stewart", "Nasser Hussain"], a:0},
{c:"Sports", q:"Yuvraj’s six sixes came off...", o:["Stuart Broad", "James Anderson", "Andrew Flintoff", "Chris Woakes"], a:0},
{c:"Sports", q:"Most Test wickets ever?", o:["Muttiah Muralitharan", "Shane Warne", "Anil Kumble", "James Anderson"], a:0},
{c:"Sports", q:"Who bowled the last over of the 2007 T20 final?", o:["Joginder Sharma", "RP Singh", "Irfan Pathan", "Sreesanth"], a:0},
{c:"Sports", q:"Messi finally won the World Cup in 2022 with...", o:["Argentina", "Brazil", "Portugal", "France"], a:0},
{c:"Sports", q:"Neeraj Chopra’s Olympic gold came in...", o:["Javelin throw", "Shot put", "Discus", "Long jump"], a:0},
{c:"Sports", q:"PV Sindhu’s Rio 2016 medal was...", o:["Silver", "Gold", "Bronze", "Fourth place"], a:0},
{c:"Sports", q:"Youngest world chess champion (2024)?", o:["Gukesh D", "Praggnanandhaa", "Magnus Carlsen", "Vishy Anand"], a:0},
{c:"Sports", q:"Most F1 world titles — 7 each — belong to Schumacher and...", o:["Lewis Hamilton", "Max Verstappen", "Sebastian Vettel", "Ayrton Senna"], a:0},
{c:"Sports", q:"A football match has how many players on the pitch (both teams)?", o:["22", "20", "24", "18"], a:0},
{c:"Weird but true", q:"A group of crows is called a...", o:["Murder", "Gang", "Mob", "Parliament"], a:0},
{c:"Weird but true", q:"The fear of long words is hilariously named...", o:["Hippopotomonstrosesquippedaliophobia", "Verbophobia", "Logophobia", "Lexiphobia"], a:0},
{c:"Weird but true", q:"Passing GO in original Monopoly gets you...", o:["$200", "$100", "$150", "$500"], a:0},
{c:"Weird but true", q:"Flamingos are pink because of...", o:["Their shrimp-and-algae diet", "Genetics", "Sunlight", "Mud baths"], a:0},
{c:"Weird but true", q:"A group of flamingos is called a...", o:["Flamboyance", "Flock", "Blush", "Parade"], a:0},
{c:"Weird but true", q:"Wombat poop is shaped like...", o:["Cubes", "Spheres", "Spirals", "Pyramids"], a:0},
{c:"Weird but true", q:"The Eiffel Tower gets taller in summer because...", o:["Metal expands in heat", "Tourists climb it", "It’s repainted", "Foundations shift"], a:0},
{c:"Weird but true", q:"Scotland’s national animal is...", o:["The unicorn", "The lion", "The stag", "The eagle"], a:0},
{c:"Weird but true", q:"Which animal has rectangular pupils?", o:["Goat", "Cat", "Owl", "Snake"], a:0}
],

/* ============ BOLLYWOOD BATTLE ============ */
bbEmoji: [
{e:'🚂🏃‍♀️🤚🌾👰', a:'Dilwale Dulhania Le Jayenge', h:'Train. Haath. Sarson ke khet.'},
{e:'3️⃣🤪🎓🏔️🍼', a:'3 Idiots', h:'Engineering + a delivery scene'},
{e:'👨🤼‍♀️🥇🇮🇳', a:'Dangal', h:'Papa + beti + gold'},
{e:'🏏🇬🇧🌧️🚫💰', a:'Lagaan', h:'One match, no taxes'},
{e:'👧🐒🇵🇰🙏', a:'Bajrangi Bhaijaan', h:'Mute kid + border'},
{e:'🏀😢💍👩‍🏫', a:'Kuch Kuch Hota Hai', h:'Basketball + wedding ring'},
{e:'👨‍👩‍👦‍👦💔🚁🏰🇬🇧', a:'Kabhi Khushi Kabhie Gham', h:'Big rich family splits'},
{e:'🤿🍅🪂🇪🇸', a:'Zindagi Na Milegi Dobara', h:'Three dares in Spain'},
{e:'🏔️🎿🍾💃❤️', a:'Yeh Jawaani Hai Deewani', h:'Trekking trip + shaadi'},
{e:'🚆🗣️👩❤️😂', a:'Jab We Met', h:'Missed train, nonstop talker'},
{e:'💪🚰🇮🇳🇵🇰', a:'Gadar', h:'THE handpump scene'},
{e:'👽📻🌍❓🕉️', a:'PK', h:'Alien asks questions'},
{e:'🏍️💨💰👮', a:'Dhoom', h:'Bikes + heists'},
{e:'♻️🎬🏆🔥', a:'Om Shanti Om', h:'Reborn for revenge + Filmfare'},
{e:'🫂🏥🤓😂', a:'Munna Bhai MBBS', h:'Jadoo ki jhappi'},
{e:'📞😂💰2️⃣1️⃣', a:'Hera Pheri', h:'Wrong number, double paisa'},
{e:'😜😜🤑👯‍♂️🔫', a:'Andaz Apna Apna', h:'Do nikamme, ek heiress'},
{e:'👻👩🚪✍️🌃', a:'Stree', h:'O behenji, kal aana'},
{e:'😡🩺💔🍾', a:'Kabir Singh', h:'Angry doctor, bad coping'},
{e:'🎤🏙️✊🧢', a:'Gully Boy', h:'Apna time aayega'},
{e:'👰✈️🗼🍾💃', a:'Queen', h:'Solo honeymoon'},
{e:'🤫😊🚲❤️', a:'Barfi!', h:'He never says a word'},
{e:'👦🎨📚✨', a:'Taare Zameen Par', h:'Ishaan + art'},
{e:'🚀👨‍🔬🏡🇮🇳💡', a:'Swades', h:'NASA to gaon'},
{e:'🕶️💪🇮🇳❄️💥', a:'Pathaan', h:'SRK is back, beard era'},
{e:'👑🗡️⛰️❓', a:'Baahubali', h:'Why did Kattappa...'},
{e:'👨‍👩‍👧📹🕳️🤫', a:'Drishyam', h:'2nd October ko kya hua?'},
{e:'🎹🙈🐰🔪', a:'Andhadhun', h:'Piano player saw nothing'},
{e:'👩🚗💩😂👴', a:'Piku', h:'Road trip + motion issues'},
{e:'🧑🥛🏥👶💰', a:'Vicky Donor', h:'Unusual donation career'},
{e:'👻🏰💃🧠🔔', a:'Bhool Bhulaiyaa', h:'Ami je tomar...'},
{e:'🤵🔫🖼️🐴🫏', a:'Welcome', h:'Majnu bhai ki painting'},
{e:'🚆😂🕺🌴🕶️', a:'Chennai Express', h:'Don\u2019t underestimate the power of...'},
{e:'🔥💧🤝💃🇮🇳', a:'RRR', h:'Naatu Naatu'}
],
bbMemes: [
{q:'"Rasode mein kaun tha?"', a:'KOKILABEN\u2019s rap — Rashi, tu thi rasode mein! (Yashraj Mukhate remix)'},
{q:'Complete it: "21 din mein paisa..."', a:'"...double." — Raju, Hera Pheri. 25 din bola toh bhi chalega.'},
{q:'"Binod." Explain the meme.', a:'A guy named Binod commented just "Binod" on YouTube — the internet made him god (2020).'},
{q:'"So beautiful, so elegant, just looking like a..."', a:'"...WOW." — saree-seller aunty, reels royalty.'},
{q:'"Moye moye" is actually from where?', a:'A Serbian song — "Dženum" (moye more) — adopted by every Indian fail video.'},
{q:'"Pawri ho rahi hai" — who started it?', a:'Dananeer from Pakistan: "Ye hamari car hai... aur ye hamari pawri ho rahi hai" + Mukhate remix.'},
{q:'"Ye bik gayi hai..."', a:'"...GORMINT." — the legendary aunty interview.'},
{q:'"Hello friends..."', a:'"...chai peelo!" — Somvati aunty.'},
{q:'Complete the painting lore: "Majnu bhai ki..."', a:'"...painting" — the horse-and-donkey masterpiece, Welcome. 25 crore ki hai.'},
{q:'"Control Uday, control..." — kaun bol raha hai?', a:'Uday Shetty himself (Nana Patekar), Welcome.'},
{q:'"Utha le re baba, utha le..." — complete it', a:'"...mereko nahi re, in dono ko utha le!" — Baburao, Hera Pheri.'},
{q:'"Jor jor se bolke sabko..."', a:'"...scheme bata de." — Raju, Phir Hera Pheri.'},
{q:'"Thala for a..."', a:'"...reason." — anything connected to 7 = MS Dhoni.'},
{q:'"Systumm" 💪 kiska catchphrase hai?', a:'Elvish Yadav. Systumm hang ho gaya.'},
{q:'"Bachpan ka pyaar" kid — what happened to him?', a:'Sahdev Dirdo — his school recording went viral, Badshah made a track with him.'},
{q:'"Kacha badam" — source?', a:'Bhuban Badyakar, a peanut seller from Bengal whose sales song conquered reels.'},
{q:'"Tuada kutta Tommy, sadda kutta..."', a:'"...KUTTA?!" — CarryMinati, YouTube vs TikTok roast.'},
{q:'"Oh bhai! Maaro mujhe maaro" — where is this from?', a:'Viral Pakistani news clip — the man getting dramatically beaten mid-report.'},
{q:'"Jethalal ka pura naam?"', a:'Jethalal Champaklal Gada. Bonus sip if you also said "Babita ji".'},
{q:'"Dekh raha hai na Binod..." — what\u2019s this format?', a:'The Kota Factory / Panchayat-style "dekh raha hai na" template for life\u2019s betrayals.'},
{q:'"Just looking like a wow" aur "so beautiful so elegant" — same aunty?', a:'Yes! One video, two immortal catchphrases.'},
{q:'"Why did Kattappa kill Baahubali?"', a:'India\u2019s biggest cliffhanger (2015-17). Answer: orders of Sivagami, manipulated by Bijjaladeva.'},
{q:'"O stree..."', a:'"...kal aana." — the only home security system that works.'},
{q:'"Aree o Sambha, kitne aadmi the?" — meme bonus: kitne THE?', a:'Do aadmi, sardar. Sholay — the OG meme.'}
],
bbDialogue: [
{q:'"Bade bade deshon mein..."', a:'"...aisi chhoti chhoti baatein hoti rehti hain, Senorita." — DDLJ'},
{q:'"Mere paas gaadi hai, bangla hai, bank balance hai... tumhare paas kya hai?"', a:'"Mere paas... MAA hai." — Deewaar'},
{q:'"Pushpa, I hate..."', a:'"...tears." — Amar Prem'},
{q:'"Kitne aadmi the?"', a:'"Sardar, do aadmi the." — Sholay'},
{q:'"Rahul, naam toh suna hoga..."', a:'— Dil To Pagal Hai (and every SRK joke since)'},
{q:'"Ja Simran ja..."', a:'"...jee le apni zindagi." — DDLJ'},
{q:'"Dosti ka ek usool hai madam..."', a:'"...no sorry, no thank you." — Maine Pyar Kiya'},
{q:'"Agar maa ka doodh piya hai toh..."', a:'"...saamne aa!" — classic masala villain bait'},
{q:'"Yeh haath mujhe de de..."', a:'"...Thakur!" — Sholay'},
{q:'"Main apni favourite hoon" — kaun?', a:'Geet — Jab We Met'},
{q:'"Uday bhai, game khatam..."', a:'"...paisa hajam." (Welcome vibes — table judges close answers)'},
{q:'"Picture abhi..."', a:'"...baaki hai mere dost." — Om Shanti Om'},
{q:'"Tension lene ka nahi..."', a:'"...sirf dene ka." — Munna Bhai'},
{q:'"Aata majhi..."', a:'"...satakli!" — Singham'},
{q:'"How’s the josh?"', a:'"HIGH SIR!" — Uri'},
{q:'"Don ko pakadna..."', a:'"...mushkil hi nahi, namumkin hai." — Don'},
{q:'"Mogambo..."', a:'"...khush hua." — Mr. India'},
{q:'"Babumoshai, zindagi badi honi chahiye..."', a:'"...lambi nahi." — Anand'},
{q:'"Crime Master Gogo naam hai mera..."', a:'"...aankhen nikal ke gotiyan khelta hoon." — Andaz Apna Apna'},
{q:'"All izz..."', a:'"...well." — 3 Idiots'},
{q:'"Zindagi mein teen cheezein kabhi underestimate mat karna..."', a:'"...I, me, and myself." (Table judges — it’s from Chennai Express region of jokes)'},
{q:'"Ek baar jo maine commitment kar di..."', a:'"...toh main apne aap ki bhi nahi sunta." — Wanted'},
{q:'"Hum ek baar jeete hain, ek baar marte hain..."', a:'"...shaadi bhi ek baar hoti hai, aur pyar bhi ek hi baar hota hai." — Kuch Kuch Hota Hai'},
{q:'"Mard ko dard..."', a:'"...nahi hota." — Mard'},
{q:'"Thappad se darr nahi lagta sahab..."', a:'"...pyar se lagta hai." — Dabangg'}
],
bbPlots: [
{q:'A guy fakes amnesia-level devotion across Europe to make a girl’s strict dad hand her over at a train.', a:'DDLJ'},
{q:'Three engineering students traumatize a dean, deliver a baby with a vacuum cleaner, and one turns out to be secretly rich in Ladakh.', a:'3 Idiots'},
{q:'A Mumbai gangster attends medical school to hug people into wellness.', a:'Munna Bhai MBBS'},
{q:'Villagers play one (1) cricket match to cancel taxes.', a:'Lagaan'},
{q:'A NASA scientist comes home to fix electricity and feelings.', a:'Swades'},
{q:'Rich kids take a Spain trip and cure their entire personalities with three activities.', a:'Zindagi Na Milegi Dobara'},
{q:'A man with 10-second... wait, 15-minute memory hunts a killer using tattoos and Polaroids, Tamil-to-Hindi edition.', a:'Ghajini'},
{q:'A mute little girl is smuggled home across a border by a man with extreme Hanuman feelings.', a:'Bajrangi Bhaijaan'},
{q:'A wedding planner falls for a bride while planning her wedding. Awkward invoices.', a:'Band Baaja Baaraat'},
{q:'Girl misses train, adopts chatty stranger as life coach, finds herself, un-finds her fiancé.', a:'Jab We Met'},
{q:'Two broke friends and one zombie outbreak at a rave in Goa.', a:'Go Goa Gone'},
{q:'A ghost needs a wedding... a woman ghost picks men at night, town writes "O Stree kal aana" on walls like it’s a group project.', a:'Stree'},
{q:'An overweight Haryanvi dad turns his daughters into world-class wrestlers against everyone’s advice.', a:'Dangal'},
{q:'A singer becomes a rockstar only after his heart is professionally demolished.', a:'Rockstar'},
{q:'A man’s tiffin goes to the wrong office desk; two lonely people fall in love via parathas.', a:'The Lunchbox'},
{q:'Policeman slaps corruption with his own surname and sunglasses physics.', a:'Singham'},
{q:'A college reunion story told at a rock concert... two eras, one band, lots of rain.', a:'Rock On!! (table judges close answers)'},
{q:'A girl’s solo honeymoon in Paris and Amsterdam after being dumped at home. Hostel roommates included.', a:'Queen'},
{q:'An invisible-man suit, a kid, and "Mogambo khush hua".', a:'Mr. India'},
{q:'Four friends, one Vegas bachelor trip... actually no, four friends on a Spain trip... no wait, it’s three friends. Deep sea, skydive, tomatoes.', a:'Zindagi Na Milegi Dobara'}
],

/* ============ MR WHITE word pairs ============ */
mrwhite: [
['Chai','Coffee'], ['Biryani','Pulao'], ['Mumbai','Delhi'], ['Beer','Whisky'],
['Shaadi','Engagement'], ['Instagram','Snapchat'], ['Gym','Yoga'], ['Goa','Manali'],
['Butter Chicken','Paneer Tikka'], ['Auto','Taxi'], ['Diwali','Holi'], ['Netflix','Cinema Hall'],
['Maggi','Pasta'], ['Cricket','Football'], ['Sharma ji ka beta','Topper'], ['Tinder','Arranged Marriage'],
['Pani Puri','Bhel Puri'], ['Honeymoon','Bachelor Trip'], ['Salman','Shah Rukh'], ['Chaiwala','Barista'],
['Monsoon','Winter'], ['Vada Pav','Burger'], ['Local Train','Metro'], ['Bhoot','Vampire'],
['Jalebi','Gulab Jamun'], ['Office','College'], ['Hangover','Headache'], ['DJ','Live Band'],
['Mehendi','Tattoo'], ['Old Monk','Vodka'], ['Rickshaw','Cycle'], ['Thali','Buffet'],
['Pyaar','Dosti'], ['Ex','Crush'], ['Selfie','Portrait'], ['Road Trip','Flight'],
['Dhaba','Fine Dining'], ['Antakshari','Karaoke'], ['Kurta','Blazer'], ['Nimbu Pani','Cola'],
['Housefull','First Day First Show'], ['Baraat','Birthday Party'], ['Chappal','Sneakers'],
['Lassi','Milkshake'], ['IPL','World Cup']
],

/* ============ CATEGORIES ============ */
categories: [
'SRK movies','Daaru brands','IPL teams + captains (any era)','Pizza toppings','Indian street foods',
'Cities with metros','Honeymoon destinations','Excuses for coming late','Bollywood villains','Cigarette-break lies',
'Things in a wedding buffet','Cuss words (mild ones only... or not)','Cartoon characters','Insta influencers you secretly follow',
'Cricket commentators','Things you say to a traffic cop','Maggi se better 2 am foods','Salman Khan movies',
'Songs with "Dil" in the title','Breakup excuses','Things in Dhruv’s fridge (he verifies)','Hangover cures',
'Pick-up lines','Places to hide from relatives at a shaadi','Web series everyone pretends to have watched',
'Things that cost under ₹100','Airport behaviours of Indian uncles','Reality shows','Chai types',
'Government office items','Mythological weapons','Auto driver dialogues','Things in a woman’s handbag',
'90s cartoons','Gym excuses','Monsoon problems','Cheap beer brands','Family WhatsApp group forwards',
'Wedding songs','Haunted places in India','Things you shout at a TV during cricket','Tourist scams',
'South Indian dishes','Dating app bios clichés','College fest events','Bhai (Salman) dialogues',
'Things Dhruv says when drunk (he cannot object)','Mountains > beaches arguments','Items at a paan shop','Bollywood moms'
],

/* ============ FLASH MATCH symbol pool ============ */
flashSymbols: ['🍺','🥃','🍋','🎲','🃏','👑','💃','🔥','🎸','🍕','🌶️','🏏','🎬','💋','🕶️','🚬','💸','🪩','🧊','🍾','🎤','🐍','🌙','⭐','🍫','☕','🦁','🛺','🎯','🧿'],

/* ============ IRISH POKER round labels ============ */
irish: {
  rounds: [
    {name:'Red or Black?', opts:['Red','Black'], sips:2},
    {name:'Higher or Lower than your first card?', opts:['Higher','Lower'], sips:4},
    {name:'Inside or Outside your first two?', opts:['Inside','Outside'], sips:6},
    {name:'Pick the Suit', opts:['♠ Spades','♥ Hearts','♣ Clubs','♦ Diamonds'], sips:8}
  ]
},

/* ============ MAFIA narrator lines ============ */
mafiaFlavor: {
  nightOpen: ['The city sleeps. Sab aankhein band.','Night falls on the casino. Heads down, no peeking — we see you.','Lights out. The table goes quiet. Eyes closed.'],
  kill: ['The Mafia opens their eyes and silently picks tonight’s target.','Mafia, wake up. Choose who’s cut off from the bar. Permanently.'],
  doctor: ['Doctor, wake up. Pick one person to save tonight.','Doctor uthe. Ek life bachao.'],
  detective: ['Detective, wake up. Point at one person — I’ll nod if they’re Mafia.','Detective, one suspicion. Choose.'],
  dayNoDeath: ['The city wakes up... and EVERYONE survived. Doctor ne bacha liya. Everyone drinks 1 in celebration.'],
  dayDeath: ['The city wakes up... and {v} didn’t. {v}, you’re out — take 3 farewell sips and enjoy the afterlife (snacks table).']
}
};
