/* Dhruv's Birthday Casino — offline-first service worker */
const CACHE = 'dbc-v4';
const CORE = [
  "./",
  "index.html",
  "app.js",
  "decks.js",
  "manifest.webmanifest",
  "assets/emoji-map.js",
  "fonts/limelight.woff2",
  "fonts/oswald-var.woff2",
  "fonts/sourcesans3-var.woff2",
  "fonts/sourcesans3-italic-var.woff2",
  "fonts/librebodoni-var.woff2",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-180.png",
  "assets/twemoji/1f0cf.svg",
  "assets/twemoji/1f1ea-1f1f8.svg",
  "assets/twemoji/1f1ec-1f1e7.svg",
  "assets/twemoji/1f1ee-1f1f3.svg",
  "assets/twemoji/1f1f5-1f1f0.svg",
  "assets/twemoji/1f303.svg",
  "assets/twemoji/1f30d.svg",
  "assets/twemoji/1f319.svg",
  "assets/twemoji/1f327.svg",
  "assets/twemoji/1f334.svg",
  "assets/twemoji/1f336.svg",
  "assets/twemoji/1f33e.svg",
  "assets/twemoji/1f345.svg",
  "assets/twemoji/1f34b.svg",
  "assets/twemoji/1f355.svg",
  "assets/twemoji/1f36b.svg",
  "assets/twemoji/1f37a.svg",
  "assets/twemoji/1f37c.svg",
  "assets/twemoji/1f37e.svg",
  "assets/twemoji/1f393.svg",
  "assets/twemoji/1f3a4.svg",
  "assets/twemoji/1f3a8.svg",
  "assets/twemoji/1f3ac.svg",
  "assets/twemoji/1f3af.svg",
  "assets/twemoji/1f3b2.svg",
  "assets/twemoji/1f3b8.svg",
  "assets/twemoji/1f3b9.svg",
  "assets/twemoji/1f3bf.svg",
  "assets/twemoji/1f3c0.svg",
  "assets/twemoji/1f3c3-200d-2640-fe0f.svg",
  "assets/twemoji/1f3c6.svg",
  "assets/twemoji/1f3cd.svg",
  "assets/twemoji/1f3cf.svg",
  "assets/twemoji/1f3d4.svg",
  "assets/twemoji/1f3d9.svg",
  "assets/twemoji/1f3e1.svg",
  "assets/twemoji/1f3e5.svg",
  "assets/twemoji/1f3f0.svg",
  "assets/twemoji/1f40d.svg",
  "assets/twemoji/1f412.svg",
  "assets/twemoji/1f430.svg",
  "assets/twemoji/1f434.svg",
  "assets/twemoji/1f451.svg",
  "assets/twemoji/1f466.svg",
  "assets/twemoji/1f467.svg",
  "assets/twemoji/1f468-200d-1f469-200d-1f466-200d-1f466.svg",
  "assets/twemoji/1f468-200d-1f469-200d-1f467.svg",
  "assets/twemoji/1f468-200d-1f52c.svg",
  "assets/twemoji/1f468.svg",
  "assets/twemoji/1f469-200d-1f3eb.svg",
  "assets/twemoji/1f469.svg",
  "assets/twemoji/1f46e.svg",
  "assets/twemoji/1f46f-200d-2642-fe0f.svg",
  "assets/twemoji/1f470.svg",
  "assets/twemoji/1f474.svg",
  "assets/twemoji/1f476.svg",
  "assets/twemoji/1f47b.svg",
  "assets/twemoji/1f47d.svg",
  "assets/twemoji/1f483.svg",
  "assets/twemoji/1f48b.svg",
  "assets/twemoji/1f48d.svg",
  "assets/twemoji/1f494.svg",
  "assets/twemoji/1f4a1.svg",
  "assets/twemoji/1f4a5.svg",
  "assets/twemoji/1f4a7.svg",
  "assets/twemoji/1f4a8.svg",
  "assets/twemoji/1f4a9.svg",
  "assets/twemoji/1f4aa.svg",
  "assets/twemoji/1f4b0.svg",
  "assets/twemoji/1f4b8.svg",
  "assets/twemoji/1f4da.svg",
  "assets/twemoji/1f4de.svg",
  "assets/twemoji/1f4f9.svg",
  "assets/twemoji/1f4fb.svg",
  "assets/twemoji/1f514.svg",
  "assets/twemoji/1f525.svg",
  "assets/twemoji/1f52a.svg",
  "assets/twemoji/1f52b.svg",
  "assets/twemoji/1f549.svg",
  "assets/twemoji/1f573.svg",
  "assets/twemoji/1f576.svg",
  "assets/twemoji/1f57a.svg",
  "assets/twemoji/1f5bc.svg",
  "assets/twemoji/1f5e1.svg",
  "assets/twemoji/1f5e3.svg",
  "assets/twemoji/1f5fc.svg",
  "assets/twemoji/1f602.svg",
  "assets/twemoji/1f60a.svg",
  "assets/twemoji/1f61c.svg",
  "assets/twemoji/1f621.svg",
  "assets/twemoji/1f622.svg",
  "assets/twemoji/1f648.svg",
  "assets/twemoji/1f64f.svg",
  "assets/twemoji/1f680.svg",
  "assets/twemoji/1f681.svg",
  "assets/twemoji/1f682.svg",
  "assets/twemoji/1f686.svg",
  "assets/twemoji/1f697.svg",
  "assets/twemoji/1f6aa.svg",
  "assets/twemoji/1f6ab.svg",
  "assets/twemoji/1f6ac.svg",
  "assets/twemoji/1f6b0.svg",
  "assets/twemoji/1f6b2.svg",
  "assets/twemoji/1f6fa.svg",
  "assets/twemoji/1f911.svg",
  "assets/twemoji/1f913.svg",
  "assets/twemoji/1f91a.svg",
  "assets/twemoji/1f91d.svg",
  "assets/twemoji/1f92a.svg",
  "assets/twemoji/1f92b.svg",
  "assets/twemoji/1f935.svg",
  "assets/twemoji/1f93c-200d-2640-fe0f.svg",
  "assets/twemoji/1f93f.svg",
  "assets/twemoji/1f943.svg",
  "assets/twemoji/1f947.svg",
  "assets/twemoji/1f95b.svg",
  "assets/twemoji/1f981.svg",
  "assets/twemoji/1f9ca.svg",
  "assets/twemoji/1f9d1.svg",
  "assets/twemoji/1f9e0.svg",
  "assets/twemoji/1f9e2.svg",
  "assets/twemoji/1f9ff.svg",
  "assets/twemoji/1fa7a.svg",
  "assets/twemoji/1fa82.svg",
  "assets/twemoji/1faa9.svg",
  "assets/twemoji/1fac2.svg",
  "assets/twemoji/1facf.svg",
  "assets/twemoji/2615.svg",
  "assets/twemoji/267b.svg",
  "assets/twemoji/26f0.svg",
  "assets/twemoji/2708.svg",
  "assets/twemoji/270a.svg",
  "assets/twemoji/270d.svg",
  "assets/twemoji/2728.svg",
  "assets/twemoji/2744.svg",
  "assets/twemoji/2753.svg",
  "assets/twemoji/2764.svg",
  "assets/twemoji/2b50.svg",
  "assets/twemoji/31-20e3.svg",
  "assets/twemoji/32-20e3.svg",
  "assets/twemoji/33-20e3.svg"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(CORE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys =>
    Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
  ).then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) return;
  // App shell: cache-first, refresh in background.
  e.respondWith(
    caches.match(e.request, {ignoreSearch: true}).then(hit => {
      const net = fetch(e.request).then(res => {
        if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(e.request, copy)); }
        return res;
      }).catch(() => hit);
      return hit || net;
    })
  );
});
